services:
  - type: web
    name: dream11-bot
    env: python
    runtime: python310  # Use 'python310' instead of 'python-3.10' for Render
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: CRICAPI_KEY
        sync: false
    disks:
      - name: data
        mountPath: "/opt/render/project/src"
        sizeGB: 1
