services:
  - type: web
    name: dream11-bot
    env: python
    runtime: python310
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: CRICAPI_KEY
        value: "4a1c0cf5-f217-44e4-aa8f-381ac1b529ea"
    disks:
      - name: data
        mountPath: "/opt/render/project/src"
        sizeGB: 1
